"use client";

import { motion } from "framer-motion";
import { ArrowUpRight, Check, ChevronRight, Droplets, Footprints, HeartHandshake, UserRound, Utensils } from "lucide-react";
import Link from "next/link";
import { useMemo, useState, type ReactNode } from "react";
import { CoachCard } from "@/components/ai/coach-card";
import { ActivityRings } from "@/components/dashboard/activity-rings";
import { AdaptiveCard } from "@/components/dashboard/adaptive-card";
import { HabitList } from "@/components/dashboard/habit-list";
import { WaterGauge } from "@/components/dashboard/water-gauge";
import { LargeTitle } from "@/components/large-title";
import { AccountNudge } from "@/components/auth/account-card";
import { MetricEntrySheet } from "@/components/metric-entry-sheet";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState, SectionHeader } from "@/components/ui/section-header";
import { Switch } from "@/components/ui/switch";
import { calculateRecoveryInsight, mealTotalsForDate } from "@/lib/calculations";
import { localDateKey } from "@/lib/date";
import { fadeRise, usePrefersReducedMotion } from "@/lib/motion";
import { demoMeals } from "@/lib/seed";
import { useBodyFitnessStore } from "@/lib/store";
import { formatNumber } from "@/lib/utils";

export default function DashboardPage() {
  const targets = useBodyFitnessStore((state) => state.targets);
  const targetsSource = useBodyFitnessStore((state) => state.targetsSource);
  const aiPlan = useBodyFitnessStore((state) => state.aiPlan);
  const meals = useBodyFitnessStore((state) => state.meals);
  const dailyByDate = useBodyFitnessStore((state) => state.dailyByDate);
  const habits = useBodyFitnessStore((state) => state.habits);
  const flexDays = useBodyFitnessStore((state) => state.flexDays);
  const circle = useBodyFitnessStore((state) => state.account.circle);
  const setCreatine = useBodyFitnessStore((state) => state.setCreatine);
  const addWater = useBodyFitnessStore((state) => state.addWater);
  const setSteps = useBodyFitnessStore((state) => state.setSteps);
  const toggleHabit = useBodyFitnessStore((state) => state.toggleHabit);
  const toggleFlexDay = useBodyFitnessStore((state) => state.toggleFlexDay);
  const [stepsOpen, setStepsOpen] = useState(false);
  const reducedMotion = usePrefersReducedMotion();

  const today = localDateKey();
  const daily = dailyByDate[today];
  const usingDemo = meals.length === 0;
  const visibleMeals = usingDemo ? demoMeals() : meals;
  const totals = mealTotalsForDate(visibleMeals, today);
  const steps = daily?.steps || (usingDemo ? 6_840 : 0);
  const water = daily?.waterMl ?? 0;
  const completedHabitIds = daily?.completedHabitIds ?? [];
  const proteinRemaining = Math.max(0, targets.proteinG - totals.proteinG);
  const waterRemaining = Math.max(0, targets.waterMl - water);
  const stepsRemaining = Math.max(0, targets.steps - steps);
  const insight = useMemo(
    () =>
      usingDemo
        ? { loggedDays: 5, averageCalories: targets.calories - 74, variance: -74, suggestedLow: null, suggestedHigh: null }
        : calculateRecoveryInsight(meals, targets),
    [meals, targets, usingDemo],
  );
  const todaysMeals = visibleMeals.filter((meal) => localDateKey(meal.loggedAt) === today).slice(0, 3);

  return (
    <main className="page-shell">
      <LargeTitle
        eyebrow={new Intl.DateTimeFormat("en-IN", { weekday: "long", month: "long", day: "numeric" }).format(new Date())}
        title="Today"
        action={
          <Button asChild variant="outline" size="icon" aria-label="Open profile">
            <Link href="/profile">
              <UserRound />

      <AccountNudge />
            </Link>
          </Button>
        }
      />

      {/*
        Mobile: one column in DOM order (hero, next action, coach, protocol, trend, fuel, circle).
        The column wrappers are `contents` below `md`, so `order-*` sorts their children in the
        page grid. From `md` they become real flex columns; at `xl` the hero spans both.
      */}
      <div className="grid gap-4 md:grid-cols-[7fr_5fr] md:grid-rows-[auto_1fr] md:gap-6">
        <motion.div variants={fadeRise} initial="hidden" animate="visible" className="min-w-0 md:col-start-1 md:row-start-1 xl:col-span-2">
          <ActivityRings
            calories={totals.calories}
            calorieTarget={targets.calories}
            protein={totals.proteinG}
            proteinTarget={targets.proteinG}
            steps={steps}
            stepTarget={targets.steps}
            onEditSteps={() => setStepsOpen(true)}
            reducedMotion={reducedMotion}
            meta={
              <>
                {targetsSource === "ai" ? (
                  <Badge variant="brand" title={aiPlan ? `Targets generated by ${aiPlan.model}` : undefined}>
                    AI plan
                  </Badge>
                ) : (
                  <Badge>Formula</Badge>
                )}
                {usingDemo ? <Badge>Sample data</Badge> : null}
                <Button asChild variant="ghost" size="sm" className="h-6 px-1.5">
                  <Link href="/profile" aria-label="Change how targets are calculated">
                    Change
                  </Link>
                </Button>
              </>
            }
          />
        </motion.div>

        <div className="contents md:col-start-1 md:row-start-2 md:flex md:min-w-0 md:flex-col md:gap-6 md:self-start">
          <motion.div variants={fadeRise} initial="hidden" animate="visible" className="order-1">
            <NextAction
              proteinRemaining={proteinRemaining}
              waterRemaining={waterRemaining}
              stepsRemaining={stepsRemaining}
              onAddWater={() => addWater(250)}
              onEditSteps={() => setStepsOpen(true)}
            />
          </motion.div>

          <motion.section variants={fadeRise} initial="hidden" animate="visible" className="order-3 mt-6 md:mt-0">
            <SectionHeader index="01" title="Daily protocol" caption="The repeatable actions that compound over time." />
            <div className="grid grid-cols-2 gap-3 sm:gap-4">
              <Card className="flex min-h-44 flex-col justify-between">
                <CardHeader className="items-center">
                  <Badge className="number-font">5 g</Badge>
                  <Switch
                    checked={daily?.creatineTaken ?? false}
                    onCheckedChange={(checked) => setCreatine(checked)}
                    aria-label="Creatine taken today"
                  />
                </CardHeader>
                <CardContent>
                  <CardTitle>Creatine</CardTitle>
                  <p className="mt-1 text-sm text-muted-foreground">{daily?.creatineTaken ? "Logged today" : "Maintain saturation"}</p>
                </CardContent>
              </Card>
              <WaterGauge valueMl={water} targetMl={targets.waterMl} onChange={addWater} />
            </div>
            <div className="mt-3 sm:mt-4">
              <HabitList habits={habits} completedIds={completedHabitIds} onToggle={toggleHabit} />
            </div>
          </motion.section>

          <motion.section variants={fadeRise} initial="hidden" animate="visible" className="order-5 mt-6 md:mt-0">
            <SectionHeader
              index="03"
              title="Fuel log"
              caption="Meals contributing to today’s output."
              action={
                <Button asChild variant="ghost" size="sm">
                  <Link href="/nutrition">
                    Log food <ArrowUpRight />
                  </Link>
                </Button>
              }
            />
            {todaysMeals.length === 0 ? (
              <EmptyState
                title="Nothing logged today"
                body="Capture a plate or add a meal manually and it will appear here."
                action={
                  <Button asChild variant="primary" size="sm">
                    <Link href="/nutrition">Log food</Link>
                  </Button>
                }
              />
            ) : (
              <Card className="overflow-hidden">
                <ul className="divide-y divide-border">
                  {todaysMeals.map((meal) => (
                    <li key={meal.id} className="flex min-h-16 items-center gap-4 px-5 py-3">
                      <div className="min-w-0 flex-1">
                        <p className="truncate text-base font-medium">{meal.name}</p>
                        <p className="number-font mt-0.5 text-xs text-muted-foreground">
                          {formatNumber(meal.proteinG)} g protein · {formatNumber(meal.carbsG)} g carbs
                        </p>
                      </div>
                      <p className="number-font shrink-0 text-lg font-semibold">
                        {formatNumber(meal.calories)}
                        <span className="ml-1 text-xs font-medium tracking-normal text-subtle-foreground">kcal</span>
                      </p>
                    </li>
                  ))}
                </ul>
                <div className="flex items-center justify-between border-t border-border px-5 py-3 text-sm text-muted-foreground">
                  <span>{usingDemo ? <Badge>Sample data</Badge> : `${todaysMeals.length} of today’s meals`}</span>
                  <span className="number-font">
                    {formatNumber(totals.proteinG)} <span className="text-subtle-foreground">g protein</span>
                  </span>
                </div>
              </Card>
            )}
          </motion.section>
        </div>

        <div className="contents md:col-start-2 md:row-span-2 md:row-start-1 md:flex md:min-w-0 md:flex-col md:gap-6 md:self-start xl:row-span-1 xl:row-start-2">
          <motion.div variants={fadeRise} initial="hidden" animate="visible" className="order-2">
            <CoachCard />
          </motion.div>

          <motion.section variants={fadeRise} initial="hidden" animate="visible" className="order-4 mt-6 md:mt-0">
            <SectionHeader index="02" title="Trend intelligence" caption="Signal over noise from your recent nutrition pattern." />
            <AdaptiveCard insight={insight} target={targets.calories} demo={usingDemo} isFlexDay={flexDays.includes(today)} onToggleFlexDay={() => toggleFlexDay(today)} />
          </motion.section>

          <motion.section variants={fadeRise} initial="hidden" animate="visible" className="order-6 mt-6 md:mt-0">
            <SectionHeader index="04" title="Circle" caption="People sharing progress with you." />
            <CirclePulse members={circle.members} pendingInvites={circle.pendingInvites} />
          </motion.section>
        </div>
      </div>

      <MetricEntrySheet key={stepsOpen ? "steps-open" : "steps-closed"} open={stepsOpen} onOpenChange={setStepsOpen} title="Today’s steps" value={steps} unit="steps" onSave={setSteps} />
    </main>
  );
}

function IconTile({ children }: { children: ReactNode }) {
  return <span className="flex size-10 shrink-0 items-center justify-center rounded-md border border-border bg-muted text-muted-foreground">{children}</span>;
}

function CirclePulse({ members, pendingInvites }: { members: ReturnType<typeof useBodyFitnessStore.getState>["account"]["circle"]["members"]; pendingInvites: number }) {
  const active = members.filter((member) => member.summary).slice(0, 3);
  return (
    <Link href="/profile/circle" className="pressable block rounded-xl">
      <Card className="flex min-h-20 items-center gap-4 px-5 py-4 transition-colors hover:bg-accent">
        <IconTile>
          <HeartHandshake size={18} />
        </IconTile>
        <div className="min-w-0 flex-1">
          <p className="text-base font-medium">Circle pulse</p>
          <p className="mt-0.5 truncate text-sm text-muted-foreground">
            {active.length ? `${active.length} ${active.length === 1 ? "person" : "people"} shared progress today` : "Invite friends and family to share goals"}
          </p>
        </div>
        {pendingInvites ? <Badge variant="warning" className="number-font shrink-0">{pendingInvites} pending</Badge> : null}
        <ChevronRight size={16} className="shrink-0 text-faint-foreground" />
      </Card>
    </Link>
  );
}

function NextAction({
  proteinRemaining,
  waterRemaining,
  stepsRemaining,
  onAddWater,
  onEditSteps,
}: {
  proteinRemaining: number;
  waterRemaining: number;
  stepsRemaining: number;
  onAddWater: () => void;
  onEditSteps: () => void;
}) {
  if (proteinRemaining > 0) {
    return (
      <NextActionRow
        icon={<Utensils size={18} />}
        title="Prioritize protein next"
        detail={
          <>
            <span className="number-font text-foreground">{formatNumber(proteinRemaining)} g</span> remaining today
          </>
        }
        action={
          <Button asChild variant="primary" size="sm">
            <Link href="/nutrition">Log food</Link>
          </Button>
        }
      />
    );
  }
  if (waterRemaining > 0) {
    return (
      <NextActionRow
        icon={<Droplets size={18} />}
        title="Hydration is next"
        detail={
          <>
            <span className="number-font text-foreground">{(waterRemaining / 1_000).toFixed(1)} L</span> remaining today
          </>
        }
        action={
          <Button variant="primary" size="sm" onClick={onAddWater}>
            +250 ml
          </Button>
        }
      />
    );
  }
  if (stepsRemaining > 0) {
    return (
      <NextActionRow
        icon={<Footprints size={18} />}
        title="Keep moving"
        detail={
          <>
            <span className="number-font text-foreground">{formatNumber(stepsRemaining)}</span> steps to your goal
          </>
        }
        action={
          <Button variant="primary" size="sm" onClick={onEditSteps}>
            Update
          </Button>
        }
      />
    );
  }
  return (
    <NextActionRow
      icon={<Check size={18} className="text-success" />}
      title="Core targets complete"
      detail="Keep the rest of the day steady."
    />
  );
}

function NextActionRow({ icon, title, detail, action }: { icon: ReactNode; title: string; detail: ReactNode; action?: ReactNode }) {
  return (
    <Card className="flex min-h-20 items-center gap-4 px-5 py-4">
      <IconTile>{icon}</IconTile>
      <div className="min-w-0 flex-1">
        <p className="text-xs font-medium uppercase tracking-[0.06em] text-subtle-foreground">Next action</p>
        <p className="mt-0.5 text-base font-medium">{title}</p>
        <p className="mt-0.5 text-sm text-muted-foreground">{detail}</p>
      </div>
      {action ? <div className="shrink-0">{action}</div> : null}
    </Card>
  );
}
